######################################################################
# Automatically generated by qmake (2.01a) Thu Jul 1 23:24:29 2010
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .
QT += phonon
# Input
HEADERS += lrcwindow.h musiclist.h widget.h
FORMS += musiclist.ui widget.ui
SOURCES += lrcwindow.cpp main.cpp musiclist.cpp widget.cpp
RESOURCES += resource.qrc
