######################################################################
# Automatically generated by qmake (2.01a) ?? 7? 23 16:00:59 2010
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += lrcwindow.h musiclist.h widget.h
FORMS += musiclist.ui widget.ui
SOURCES += lrcwindow.cpp main.cpp musiclist.cpp widget.cpp
RESOURCES += resource.qrc

QT += phonon
